
# Data Dragon
DDUrl =https://ddragon.leagueoflegends.com/cdn/
DDVer =12.14.1

# summoner id 조회
smnUrl = https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/

# tier 조회
tierUrl = https://kr.api.riotgames.com/lol/league/v4/entries/by-summoner/

# 현재 게임 중 여부 current
currentUrl = https://kr.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/

# matchId 리스트 출력
matchesUrl = https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/

# match 당 디테일 조회
matchDtlUrl = https://asia.api.riotgames.com/lol/match/v5/matches/